#let variables = (
  TP: "True Positive",
  TN: "True Negative",
  FP: "False Positive",
  FN: "False Negative",
  L: "Menge an Klassen",
  N: "Anzahl an Iterationen",
  P: "Menge an vorhergesagten Klassen",
  H: "Menge an tatsächlichen Klassen",
  b: "vorhergesagter Text",
  d: "Referenztext",
  "\u{03C9}": "Wort",
  B: "Menge aller n-gramme im vorhergesagten Text",
  D: "Menge aller n-gramme im Referenztext",
  c: "Klasse",
  SE: "Standardfehler",
  "\u{039B}": "Textlänge",
  r: "Pearson-Korrelationskoeffizient",
  k:"Anzahl der betrachteten Chunks"
)